### ISSUE TITLE
Configuration UI

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.banking#102]
To enable a regular user to adjust the configuration of the various components, we want to create a configuration UI consisting of two parts:
1. A configuration panel where you can add/remove and enable/disable plugin instances of the four types:
   - Importer
   - Analyser / Matcher
   - PostProcessor
   - Exporter
   
   You can see a mockup version of this when you select the `Configure` option in your `Banking` menu.
2. An editor for the configuration of the individual instances, featuring:
   - Form elements for common fields (e.g. a checkbox for the `auto_exec` parameter present in all matchers)
   - a graphical JSON editor like [JSONMate](http://jsonmate.com/#editor-container) for the configuration
   - inline documentation for the parameters of the current plugin implementations
   - integration of the [example configuration database](https://github.com/Project60/org.project60.banking/tree/master/configuration_database)
   - the plugin implementations can provide their own configuration panels, overwriting the default configuration editor. I will not implement this for the current implementations, though.

**Comment by bkaless** [comment]
thanks for the specification.

a link or button like "handle this payment every time as follows"  in the process-section would be nice.

**Comment by systopia** [comment]
@bkaless Please elaborate in another ticket

**Comment by bkaless** [comment]
see 

https://github.com/Project60/org.project60.banking/issues/105

I hope, I marked the issue properly.

**Comment by sebastian-leidig** [comment]
Hi there, I am trying to get the extension to work at the moment and would be willing to implement the basic functionality for the current config UI mockup (for now maybe just the simple part of listing/adding/editing an instance to avoid any direct database interactions for the user).

What's the status on this? Any important remarks - or shall I just play with the code for `Manager.php` on my fork and see where I'll end up?

**Comment by systopia** [comment]
Hi @sebastian-leidig. We actually have a draft and mockups ready, and we're about to send out an email to all our (known) CiviBanking users asking for feedback and funding. This should happen within the next month or so.

**Comment by systopia** [comment]
released with ``0.6.alpha1``
