### ISSUE TITLE
Ampersand on URLs breaks the/some links

### ISSUE THREAD

**Issue by VangelisP** [Project60/org.project60.banking#119]
I had an issue where the ampersand on urls would be converted to html entity (&amp;) , thus braking the links.
This happened after eg. a successful importation and by clicking on "Show results" page.
Similarly, while selecting individual transactions and pressing "Process", the redirection would brake as well, as it was cripling the url.

Civicrm 4.6.6
Drupal 7.x

**Comment by systopia** [comment]
@VangelisP: I have not observed this so far, could you please provide detailed steps to reproduce the issue?

**Comment by VangelisP** [comment]
I did some tests after patching, no issues appeared on other pages.

CiviCRM: 4.6.6
Drupal: 7.x

**Comment by systopia** [comment]
@VangelisP: That's great!  Is that already in this repository? Could you please link the commit for me?

**Comment by VangelisP** [comment]
Here you are @systopia  : https://github.com/VangelisP/org.project60.banking/commit/015cdfae8c71ff38213b354117c0fe5d201a8765

I have a merge request for this one set-up already

**Comment by systopia** [comment]
Ah, sorry - I forgot. I'll merge [PR-120](https://github.com/Project60/org.project60.banking/pull/120) once 0.5.2 is released (currently beta-testing).

**Comment by VangelisP** [comment]
Works properly

**Comment by systopia** [comment]
Great!
