### ISSUE TITLE
Regex Lookup doesn't bring back customfields

### ISSUE THREAD

**Issue by VangelisP** [Project60/org.project60.banking#126]
In case your request from a lookup filter is an internal field, everything is good. 
But in case the request is a custom field, lookup brings back nothing.
I've slightly modified the code so that it actually brings back whatever is requested. It can be extended also to bring multiple fields/custom fields.

Here's the tiny patch made on my fork:
https://github.com/VangelisP/org.project60.banking/commit/2061d286186fb59ef84e9787e6f840866dfa7558

**Comment by systopia** [comment]
This patch has been merged into master with https://github.com/Project60/org.project60.banking/commit/102b5b419ca43c2f9372ecaf418aace781c10bc2 and was released with 0.5.2rc2
