### ISSUE TITLE
json for Dutch camt053 xml files

### ISSUE THREAD

**Issue by FundingWorks** [Project60/org.project60.banking#132]
Does anybody have a json for the Dutch format camt053 file. I've tried the belgium json in the config directory for my Dutch camt053 files but that doesn't work. Most likely it doesn't work for big Belgium files either. It only works in case of a single transaction per Entry. Since one entry can contain multiple transactions all information is placed in single variables. F.i. all names of a batch in a single Party variable. All IBANS of an entry in a single _party_IBAN. I've included a screenprint. The 9 euro is the amount of the first transaction. 

If there's only one transaction per entry, files are imported correctly.

What am I missing here? I hope you can help me.

Cheers,
Frank

![screen shot 2015-12-27 at 21 44 04](https://cloud.githubusercontent.com/assets/16131721/12012037/01283544-ace7-11e5-8326-42e80d3c6342.png)

**Comment by systopia** [comment]
Hi @FundingWorks. I just added another, extended version of our json file. We developed it to be able to better deal with SEPA transactions. See if it fixes your problem.

If it doesn't, which is quite likely, you can contact us directly (info@systopia.de) and we can look into your particular issue.

**Comment by systopia** [comment]
Closed due to inactivity
