### ISSUE TITLE
For Membership suggestions always the first suggestion is executed regardless of selection

### ISSUE THREAD

**Issue by sleidig** [Project60/org.project60.banking#148]
When I import transactions for a contact who has multiple memberships the Membership Matcher correctly offers a suggestion for each membership. However, regardless of which suggestion is selected the created contribution is always linked to the membership of the first suggestion.

**Comment by sebastian-leidig** [comment]
Problem seems to be that the id/hash is the same for all membership suggestions. The PR #149 fixes this and it works properly for me now.
