### ISSUE TITLE
Use of php split() is deprecated / deleted

### ISSUE THREAD

**Issue by baernm** [Project60/org.project60.banking#170]
In function getPropagationValue in CRM_Banking_PluginModel_Matcher there is a function call to php function split, which is deprecated since 5.3 and deleted since 7.0.

Possible fix: use preg_split instead.

php Error: Call to undefined function split() in CRM_Banking_PluginModel_Matcher->getPropagationValue()

**Comment by DanielvV** [comment]
Got the same problem and created pull request: #169

**Comment by DanielvV** [comment]
@baernm Should be fixed in master. Can you confirm?

**Comment by baernm** [comment]
@DanielvV yes confirmed, thank you!
