### ISSUE TITLE
Extensions isn't installable under 4.7.22

### ISSUE THREAD

**Issue by bkaless** [Project60/org.project60.banking#175]
I have the same error on installation as the Direct Debit extension:

https://github.com/Project60/org.project60.sepa/issues/443

**Comment by DanielvV** [comment]
@bkaless Should be fixed in master. Can you confirm?

**Comment by bkaless** [comment]
Yes, the current master is installable in 4.7.22

**Comment by DanielvV** [comment]
bkaless: Great, go ahead and close this issue.
