### ISSUE TITLE
Restrict import bank account lookup

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.banking#178]
It would be good to restrict the bank account lookup that the importer performs by 
 * contact IDs, and/or:
 * bank_account IDs

This way we don't have to deal with problems if there are multiple accounts with the same references.

**Comment by DanielvV** [comment]
Does this mean that if there are two contacts with the same bankaccount, there will be two 99% matches instead of none?

**Comment by systopia** [comment]
> Does this mean that if there are two contacts with the same bankaccount, there will be two 99% matches instead of none?

Yes. But this ticket is about something else. It refers to the initial assignment of the transaction to the two bank accounts at *import time*. We had issues that the the organisation's bank account was used in other contexts, and thus the transaction (and therefore the whole statement) wasn't assigned to that account. Now you can restrict that search to your organisation(s) and the result should be unique.

**Comment by systopia** [comment]
released with ``0.6.alpha1``
