### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by danielvv** [Project60/org.project60.banking#187]
Was fixed before (I think it was #170) but came back, among other problems.
One of the following pull requests fixes this: #182 #183 #184

**Comment by systopia** [comment]
@danielvv: I think I have all the missing bits in ``master`` now, would you have the time to confirm? If so, I'll releas this as ``0.6.beta3``, and then after some time without related bug reports, as ``0.6``

**Comment by danielvv** [comment]
Yes, everything works as expected using current master with PHP7. This issue can be closed when 0.6 is out I guess.

**Comment by systopia** [comment]
Thanks again, @danielvv

**Comment by systopia** [comment]
released with ``0.6``
