### ISSUE TITLE
Install with default configuration

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.banking#202]
It would be really nice if CiviBanking installed with a default importer/matcher configuration to get people started. This could then also, potentially, be referred to in @ErikHommel 's documentation.

**Comment by jaapjansma** [comment]
Possibly the default option matcher and the dummy importer?

**Comment by systopia** [comment]
Well, I was thinking CAMT.53 XML (fairly standard) and a simple CSV importer (with some hints on how to adapt in the description). And then maybe a RegeMatcher deriving financial_type and payment_instrument to feed a create contribution matcher. And yes, of course also the default options. Just to get people started. What do you think?

**Comment by eth4ever** [comment]
I think for default matchers the first step is to improve the manual matcher in the way that when you select a contact, the matcher automatically shows  existing (not completed) contributions.
Then you can choose which contribution(s) are related to the payment or create a new one.

**Comment by systopia** [comment]
>  improve the manual matcher in the way that when you select a contact, the matcher automatically shows existing (not completed) contributions.

That is definitely **not** the idea of the default matcher, but there is no reason we can't have another matcher doing this. @eth4ever: If this is what you need/want, please create an extra ticket for it.

**Comment by jaapjansma** [comment]
> Well, I was thinking CAMT.53 XML (fairly standard) and a simple CSV importer (with some hints on how to adapt in the description). And then maybe a RegeMatcher deriving financial_type and payment_instrument to feed a create contribution matcher. And yes, of course also the default options. Just to get people started. What do you think?

Sounds like a better option.

**Comment by systopia** [comment]
There's now a simple default configuration in ``master`` that gets installed with installation or upgrade - unless you already have a configuration of course.

@ErikHommel: Could you have a look at this?

**Comment by systopia** [comment]
@VangelisP, could you have a look, please?

**Comment by VangelisP** [comment]
@systopia Looks like everything works ok, configurations are being correctly prepopulated. I will investigate a little bit some other scenarios as well (just in case).

**Comment by systopia** [comment]
Thanks @VangelisP. Betty confirmed it as well, so I'm closing the ticket.
