### ISSUE TITLE
Add contribution notes post-process

### ISSUE THREAD

**Issue by psampont** [Project60/org.project60.banking#208]
It would be nice to be able to add notes to the contribution via a post-process.

For example, to be able to copy the purpose as a note to a contribution.

**Comment by systopia** [comment]
You should be able to just add 
```
"btx.purpose": "contribution.note",
```
to the ``value_propagation``.

@psampont: Could you try this?

**Comment by psampont** [comment]
Sorry, I don't see your response.

Yes, it's work in value_propagation. Thank you.

**Comment by psampont** [comment]
I didn't see your answer.

Yes, it's work in value_propagation. Thank you.

**Comment by systopia** [comment]
Great
