### ISSUE TITLE
Can't have a plugin with "\("

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.banking#216]
Hi,

I want to match a name "bla (bla)", the ignore matcher is a regex, so I'm trying to write it as "bla \(bla\)"... but when I save it, it ignores it and doesn't save.

**Comment by jaapjansma** [comment]
This has something to do with escaping in json, so probably use a \ before special characters.

**Comment by tttp** [comment]
ah, I'm stupid, it's \\ indeed, thanks!
