### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by cfabrice** [Project60/org.project60.banking#234]
Hello, we are trying to use your extension for importing CAMT 54 in Switzerland. 
For the moment, we are just trying to make your extension work on a wordpress install and we tried on a Drupal instance. 
We've checked the documentation, tried to configure our instances as best as we understood but in both instances we get the same error while importing a file (wether a camt 53 or 54): 
"Notice: Undefined property: stdClass::$namespaces in CRM_Banking_PluginImpl_Importer_XML->initDocument() (line 79... in ... XML.php

We use last version of Wordpress on PHP 7.1 and Drupal 7.6 on php 7.1 and mysql 5.7
Any help to configure this would be appreciated, we can provide an example camt 54 file. 
Thank you.

**Comment by jensschuppe** [comment]
Closing as outdated. If still relevant, this seems like a configuration issue. You might want to check the revised documentation on XML importers [here](https://docs.civicrm.org/banking/en/latest/configuration/plugins/importers/xml/).
