### ISSUE TITLE
Refactor menu routine

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.banking#239]
The menu generation routine in CiviBanking is old and fragile, time to use the ``civix`` helpers. Also, there should be an icon in CiviCRM 5.6+

**Comment by sluc23** [comment]
FYI: related issue on CiviRules --> https://lab.civicrm.org/extensions/civirules/issues/11

**Comment by jaapjansma** [comment]
There seems also be an issue with the new menu in civicrm (saving CiviBanking configuration does not work anymore since CiviCRM version 5.12).

**Comment by bjendres** [comment]
@jaapjansma I'll assume your #252 fixed it, right? Then it should be in ``0.7-alpha7``

**Comment by jaapjansma** [comment]
In #252 I fixed the fatal error. I did not refactor the menu items.

**Comment by bjendres** [comment]
Thanks @jaapjansma

**Comment by bjendres** [comment]
Released with ``0.7``
