### ISSUE TITLE
Extsiting contribution matcher: lookup contact by IBAN or Contact ID field

### ISSUE THREAD

**Issue by jaapjansma** [Project60/org.project60.banking#244]
**The context of this issue:**

0. In CiviCRM a pending contribution is created and the client is informed that he/she can wire the money with a payment description which contains the contact ID and the Contribution ID. E.g. 000456-001267 (456 = contact id, 1267 = contribution id)
1. The client wires the mony with manual bank transfer. 
2. The payment description contains a reference to the contact_id and the contribution_id
3. The transaction also holds the IBAN of the client

**What we want to achieve:**

1. A 100% match with the existing contribution matcher which is 100% when both contact id as contribution id are found
2. If contact id is invalid or not found, then we want the existing contribution matcher lookup the contact by their IBAN
3. If a contact lookup with an invalid IBAN fails, then the existing contribution could be looked up by the name of the contact

**Why the name lookup is not sufficient?**

Because a name like John Smith is too common to make possible positive match. In other words too many matches show up. 

**What needs to be done?**

1. Add a configuration option to the existing contribution matcher which holds the name of the contact_id list field. In a similar way existing contribution_ids could be provided to the existing contribution matcher. 

Maybe this one is related to #140

**Comment by bjendres** [comment]
Yes, it is related to #140. But by convention, the ``contact_id`` field is evaluated as a "100%" contact match anyway, so you can just use an analyser to set that to the right contact ID.

@jaapjansma Doesn't that solve your problem already?

**Comment by jaapjansma** [comment]
Yes the contact_id parameter solves my problem.

**Comment by bjendres** [comment]
@jaapjansma Let me know if it doesn't work...
