### ISSUE TITLE
Question: Membership matching with analyzers

### ISSUE THREAD

**Issue by marcelklehr** [Project60/org.project60.banking#263]
Does membership matching actually take into account contact_id values that have been set by analyzers? I had the impression it does it's own sweep for contacts by btx.name and simply goes through the memberships they have.

**Comment by jensschuppe** [comment]
The [Membership matcher](https://github.com/Project60/org.project60.banking/blob/master/extension/CRM/Banking/PluginImpl/Matcher/Membership.php) identifies eligible contacts via
https://github.com/Project60/org.project60.banking/blob/e6f1d6bc0f08e2a1b6795975ade0cf046bda8bda/extension/CRM/Banking/Matcher/Context.php#L54
which takes into account
- `lookup_contact_by_name`
- `external_identifier` (with a 100% probability)
- `contact_id` (with a 100% probability)
- account owner

For each contact found, the matcher fetches memberships that match the given configuration parameters.

@marcelklehr If that does not answer your question, feel free to reopen this issue.
