### ISSUE TITLE
Existing contribution matcher: lower percentage if contribution includes a time

### ISSUE THREAD

**Issue by jaapjansma** [Project60/org.project60.banking#279]
**How to reproduce**

1. Create a pending contribution and include a certain time
2. Setup civi banking to match this contribution
3. Import a bank file to match this contribution with the exact date but no time

**Actual result**
The suggestion has a percentage lower than 100% (something like 99%)

**Expected result**
A 100% suggestion as the contribution is on the same date

**Comment by jensschuppe** [comment]
This should be a configurable option in the matcher configuration.
