### ISSUE TITLE
Remove further warnings of 'sizeof'

### ISSUE THREAD

**Issue by VangelisP** [Project60/org.project60.banking#283]
Hiya @bjendres !!

I've noticed that during a CSV import on PHP 7.2 and with version 0.7-alpha7, for every line that i import, i get

```php
Warning : sizeof(): Parameter must be an array or an object that implements Countable in CRM_Banking_PluginImpl_Importer_CSV->import_file() (line 128 in /extensions org.project60.banking/extension/CRM/Banking/PluginImpl/Importer/CSV.php).
```
I noticed that for some reason, on line 128 we try to count a string:

```php
      $bytes_read += sizeof($line) * sizeof($config->delimiter);
```

Shouldn't we do `strlen($config->delimiter)` instead ?

I will produce a PR for this, if what I write is acceptable.

**Comment by bjendres** [comment]
This should've been done with #259. Did you not see that, or did I miss anything there?

**Comment by VangelisP** [comment]
No, it refers to another line, a few lines above the fix of #259 , unless i'm missing something..

**Comment by VangelisP** [comment]
Ok, my bad, this is already being implemented on master. I thought I was seeing a squashed commit (which wasn't).

Sorry about that, we can close the issue.

**Comment by bjendres** [comment]
> Sorry about that

Never be sorry for proposing an improvement :) Hope you had a good new Year!

**Comment by VangelisP** [comment]
> > Sorry about that
> 
> Never be sorry for proposing an improvement :) Hope you had a good new Year!

I tried to be very optimal and punctual to my suggestion but I failed because I misread the code :)

Mine was great with lots of .. :beer: :beer: :beer: , hope yours as well !

**Comment by bjendres** [comment]
> Mine was great with lots of .. beer beer beer , hope yours as well !

Yes indeed. See you soon (I hope)!
