### ISSUE TITLE
Approaches on treating malformed CSV files

### ISSUE THREAD

**Issue by VangelisP** [Project60/org.project60.banking#285]
Hello @bjendres 

I'm facing this situation: A bank is exporting CSV statements where they do not use quotes for enclosing their columns and they use commas for separating them. One description field is including a comma thus breaking the columns after this column. One of the columns that follows is the amount and another is the currency.

Result when importing: "broken" transaction, showing with 0 amount, resulting in manual processing.

I've seen it multiple times from different providers and the problem is that banks are not flexible at all on changing this or delivering other formats to the customer.

I'm trying to find a way to bypass this issue. Currently I can see 2 approaches:

1) Leave it as-is and it goes for manual processing. During manual processing, when the user opens the 'test' contribution popup page, they can use the amount field to add the proper amount and save the contribution. I need to investigate this a little bit further because I got reports that contribution remains as 'test' when someone is changing the amount on the popup contribution page and saves it.

2) Implement some sort of pre-check during import and if some fields do not validate or throw error, do a set of custom actions and re-check. One action that pops out of my mind would be for example some column shifting and retry until something valid appears. Ie. for amount -> integer, for currency -> string.

What are your thoughts on this? Did you face this issue in the past?

**Comment by VangelisP** [comment]
I will close this issue as it makes no sense. Looks like i'm trying to fix the impossible and overthinking it :smile: 

Fixes manually per "broken" transaction could be applied with the Default Options Matcher successfully.

**Comment by bjendres** [comment]
Hi @VangelisP. I'm sorry for dropping the ball on this one... Let me know if there's still something you'd need from me :)

**Comment by VangelisP** [comment]
No worries @bjendres , I noticed a side-effect on the manual processing (point 1 in my initial thread) but i will treat it as a separate issue once I confirm it.
