### ISSUE TITLE
Payments are not recorded in Contribution

### ISSUE THREAD

**Issue by omazany** [Project60/org.project60.banking#299]
Currently the DefaltOptions and ExistingContribution Matcher do not record payments in the reconciled Contribution. Only Contribution status is changed. Is this desired behaviour? The Payments were recorded previously.

**Comment by omazany** [comment]
Ok this seems to be only on my fork and in case the Contribution is not being set as Completed but Partially paid. Setting the Contribution to Complete status seems to record the payment automatically.

**Comment by jensschuppe** [comment]
@omazany Seems there's no problem anymore. Otherwise, please reopen this issue.
