### ISSUE TITLE
CSV Importer doesn't work with UTF8 encoded file

### ISSUE THREAD

**Issue by martst** [Project60/org.project60.banking#300]
Paypal Completed Payment reports are now encoded with the 3 byte UTF8 BOM at the start. This stops the fgetcsv file read working correctly. Adding the following code to the import_file function in CSV.php after the fopen solves the problem
`$bom = "\xef\xbb\xbf";
if (fgets($file, 4) !== $bom)
        rewind($file);`

**Comment by being-peace** [comment]
I created a pull request: https://github.com/Project60/org.project60.banking/compare/master...being-peace:patch-2

I have not added the BOM-Skipping in the sentinel test, perhaps someone wants to test for the BOM. I hope this is appropriate.

**Comment by wintermoor** [comment]
Solution is working with fresh PayPal CSV. Thanx a lot!

**Comment by bjendres** [comment]
#330 doesn't seem to work in all scenarios, so I'm testing an improved version with branch ``issue/300_2``

**Comment by bjendres** [comment]
released with ``0.8.2``
