### ISSUE TITLE
Summary field in default options matcher shows "NaN"

### ISSUE THREAD

**Issue by mmgit** [Project60/org.project60.banking#301]
the summary field allways shows **NaN** but should show the sum of the created contributions

![grafik](https://user-images.githubusercontent.com/1378433/89289830-2be33c80-d658-11ea-827f-e09212e5be8a.png)

**Comment by bjendres** [comment]
Thanks @mmgit, it seems to work just fine, and I finally pulled this. I don't why it took so long for somebody else to be bothered by this...

**Comment by bjendres** [comment]
will be released with ``0.8``

**Comment by jensschuppe** [comment]
I had raised this in #254 already, which I'll mark as a duplicate of this.

Also, this issue seems to be `status:fixed`, right @bjendres?

**Comment by bjendres** [comment]
> Also, this issue seems to be `status:fixed`, right @bjendres?

yes
