### ISSUE TITLE
How to add an contribution id to the contribution_list

### ISSUE THREAD

**Issue by MarcMichalsky** [Project60/org.project60.banking#303]
Hello @bjendres,

we tried all week to get a Contribution Matcher working that adds an id to the `contribution_list`. We identified the contribution id by looking up the transaction id.

I added this section to the Contribution Matcher configuration:

```JSON
  "contribution_list": [
    "btx.contribution_id"
  ],
```
`btx.contribution_id` is the field in which I copied the return of the lookup action. I am quite sure that the field contains the right value because it shows up in the details section when reviewing the bank transactions.

After hours of testing I, could you please tell me if I am totally on the wrong track with this?
Thanks!

**Comment by bjendres** [comment]
Hi @MarcMichalsky. 

The ``contribution_list`` parameter the "existing contribution" matcher is looking for a comma separated list of contribution IDs to use as input. I can see two potential issues with your configuration:
* it's not supposed to be an array, it's expecting a string
* while the ``btx.`` prefix *should* work, I've always used it without it.

If any those fix your issue, please create a PR for the documentation, so others won't run into the same issue.

**Comment by MarcMichalsky** [comment]
Okay, I can get the id into the list if I copy it there within the same regex matcher.
This alone seems to have no effect at all. What would I have to do in the contribution matcher?

regex matcher
```JSON
{
  "rules": [
    {
      "comment": "Erkennt Transaktions-ID",
      "fields": [
        "trxn_id"
      ],
      "pattern": "/^(Sofort-Spende Allge )(?P<trxn_id_matched>[A-Z0-9]{1,10})\\s?$/",
      "actions": [
        {
          "action": "copy",
          "from": "trxn_id_matched",
          "to": "trxn_id"
        },
        {
          "action": "lookup:Contribution,id,trxn_id",
          "from": "trxn_id",
          "to": "contribution_id"
        },
        {
          "action": "copy_append",
          "from": "contribution_id",
          "to": "contribution_list"
        },
        {
          "action": "set",
          "value": ",",
          "to": "id_seperator"
        },
        {
          "action": "copy_append",
          "from": "id_seperator",
          "to": "contribution_list"
        }
      ]
    }
  ]
}
```

details section
![Screenshot_2020-08-13 Review Bank Transaction CiviCRM forumZFD(1)](https://user-images.githubusercontent.com/24728186/90103773-582b4700-dd43-11ea-8976-c8507b732348.png)

**Comment by bjendres** [comment]
Hi @MarcMichalsky. Sorry I dropped the ball on this one.

Something like
```
"contribution_list": "online_donation_contribution_id"
```
in the configuration of your existing contribution matcher (``matcher_contribution``) should suffice, but keep in mind that all the other restrictions will still be applied (see [HERE](https://github.com/Project60/org.project60.banking/blob/297656f73b8a4aa4f4bba4f234d472dd389d367c/extension/CRM/Banking/PluginImpl/Matcher/ExistingContribution.php#L89-L157)).

Unfortunately, the existing contribution matcher doesn't have logging (like [HERE](https://github.com/Project60/org.project60.banking/blob/297656f73b8a4aa4f4bba4f234d472dd389d367c/extension/CRM/Banking/PluginImpl/Matcher/SepaMandate.php) or [HERE](https://github.com/Project60/org.project60.banking/blob/297656f73b8a4aa4f4bba4f234d472dd389d367c/extension/CRM/Banking/PluginImpl/Matcher/RegexAnalyser.php)) yet. Maybe adding that would be as starting point to see what's going on. And then creating a PR for it, obviously ;-)

**Comment by MarcMichalsky** [comment]
The solution here was to add the matched `contribution_id` to the required values (with a leading `btx.`).

## RegEx Analyser
```JSON
{
  "rules": [
    {
      "comment": "Matches transaction id",
      "fields": [
        "trxn_id"
      ],
      "pattern": "/^P<twingle_trxn_id_matched>[A-Z0-9]{1,10})\\s?$/",
      "actions": [
        {
          "action": "copy",
          "from": "twingle_trxn_id_matched",
          "to": "twingle_trxn_id"
        },
        {
          "action": "lookup:Contribution,id,trxn_id",
          "from": "twingle_trxn_id",
          "to": "twingle_contribution_id"
        }
      ]
    }
  ]
}
```

## Contribution Matcher
```JSON
{
  "generate": 1,
  "auto_exec": 0.9,
  "threshold": 0.1,
  "mode": "default",
  "accepted_contribution_states": [
    "Pending"
  ],
  "required_values": [
    "btx.twingle_contribution_id"
  ],
  "contribution_list": "twingle_contribution_id"
}
```
When I got some time, I will prepare a documentation and do a PR.
