### ISSUE TITLE
CSV Importer - batch reference parameters

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.banking#308]
Currently the bank statement ``reference`` generated by the CSV importer will only replace the standard tokens ``{md5}``, ``{starting_date}`` and ``{ending_date}``.

It should also, if a title template is provided, replace arbitrary tokens from the last processed CSV row.

Also, the filename should be available to processing.

**Comment by jensschuppe** [comment]
@bjendres This was merged with 03f05defbc5e0cf0955941d814d40ddb963296a5 - is this still `status:needs work`?

**Comment by bjendres** [comment]
released with ``0.8.0``
