### ISSUE TITLE
Link banking transactions with related contributions

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.banking#312]
We would like to introduce a link table that links a banking transaction with all (0+) relevant contributions. 

This would also include a migration of the existing (implicitly stored) data, and a link in the contribution view.

**Comment by jensschuppe** [comment]
Adding `status:fixed` since it got merged into `master` already. @bjendres Feel free to pick the correct status label if that's not correct.

**Comment by bjendres** [comment]
It's still being tested with GP, but the status fixed is ok, anyway

**Comment by bjendres** [comment]
released with ``0.8.0``
