### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by niklaskar** [Project60/org.project60.banking#316]
When accessing any page of the CiviBanking Plugin via menu i get a "Page not found" error.
CiviCRM 5.32.2
Drupal 8.91
Server is civi.local (LAN routing via hosts)
Path trying to access: http://civi.local/civicrm/banking/dashboard
Access works if another civicrm/ is added to the path, eg. http://civi.local/civicrm/civicrm/banking/dashboard
Same problem for Sepa extension.

**Comment by jensschuppe** [comment]
Seems like your host setup does not use the correct document root. This would apply to all Drupal paths, not just CiviCRM. Anyway, this doesn't seem to be an issue with CiviBanking at all.
