### ISSUE TITLE
Display postprocessor results in executed suggestions

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.banking#321]
Suggestions should display post processor results, just as they do with suggestion results.

Post processors should therefore implement the `visualize_execution_info()` method, which should be abstracted into the `CRM_Banking_PluginModel_BtxBase` base class instead of `CRM_Banking_PluginModel_BtxBase` only.

`CRM_Banking_Matcher_Suggestion::visualize_execution` should then collect visualized execution results from all postprocessors and append them to the matcher's visualized result.

**Comment by jensschuppe** [comment]
With a6d8f20768adee44ff31e0e06ef7a2794bee5ce4, all postprocessors will report their name, regardless of wether they were actually executed. `CRM_Banking_PluginModel_PostProcessor::processExecutedMatch()` should log what has been done during postprocessor execution in the suggestion object. `CRM_Banking_PluginModel_PostProcessor::visualizeExecutedMatch` should then only return something when it has actually been executed.

**Comment by jensschuppe** [comment]
Postprocessors will now be listed as potentially executed when they do not explicitly implement the visualisation. Postprocessors that do, can distinguish their results by returning either a concrete result as an array (and visualize that), or `FALSE` for denoting that they didn't execute at all, or `NULL` for not being sure (which is also the fallback for Postprocessors not implementing the visualisation). In the latter case, the wording is "might have been executed" for those plugins.

**Comment by bjendres** [comment]
released with ``0.8.0``
