### ISSUE TITLE
Add a description of to-be-executed post processors to suggestions

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.banking#325]
Currently, post processors are intransparent to the user. Each suggestion should indicate which post processors will (likely) be executed after processing the suggestion.

**Comment by jensschuppe** [comment]
The `CRM_Banking_PluginModel_PostProcessor` base class will show the post processor's name if it is likely to be executed. Post processor implementations should override the `CRM_Banking_PluginModel_PostProcessor::previewMatch()` method and return something more specific about what it will be doing with the executed match.

**Comment by jensschuppe** [comment]
This is now implemented as follows:
- Active post processors are being checked for whether they are likely to be executed. The contribution-related checks are being skipped (since there aren't any contributions at preview time). The `CRM_Banking_PluginModel_PostProcessor::shouldExecute()` method is extended with a boolean parameter `$preview` so that post processor implementations can return different results depending on that.
- There is a new method `CRM_Banking_PluginModel_PostProcessor::previewMatch()` to be implemented by post processors. The base method returns an empty string when `CRM_Banking_PluginModel_PostProcessor::shouldExecute()` returns `TRUE`. Implementations may return any markup to be shown in the preview, or `NULL` to indicate that the post processor will not be executed for the suggestion. This should be implemented as precisely as possible, or display something describing any uncertainty (e.g. "This post processor _might_ ..."), so the user can rely on it and will not be faced with different post processing results. Post processor results should be visualized, see #321.
- The preview is being shown in a collapsed accordion element in the top right corner of each suggestion. When collapsed, only the number of to-be-executed post processors is shown (e.g. "2 Post processors"). Expanding the accordion will place it below the suggestion markup and display whatever markup post processors are providing, or only their name, if they don't have a specific implementation of `CRM_Banking_PluginModel_PostProcessor::previewMatch()`.

As an example, the `CRM_Banking_PluginImpl_PostProcessor_AddressUpdate` and `CRM_Banking_PluginImpl_PostProcessor_MembershipExtension` post processors are implementing the `previewMatch()` method, returning different markup depending on their configuration.

This will be released with `0.8`.

**Comment by bjendres** [comment]
released with ``0.8.0``
