### ISSUE TITLE
Account lookup broken if multiple accounts match

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.banking#332]
When identifying the contact one of the first default things is to look for a contact with a unique bank account reference, and that seems to be working well. However, if the account (reference) is used by multiple people, this doesn't work. There is another code path (``getAccountContacts()``) to do this secondary search, but this is broken.

**Comment by jensschuppe** [comment]
Adding status:fixed since it got merged into master already. @bjendres Feel free to pick the correct status label if that's not correct.

**Comment by bjendres** [comment]
In this case, as well, there is no third party confirmation that it's correct and working, but it's ok to set the status

**Comment by bjendres** [comment]
released with ``0.8.0``
