### ISSUE TITLE
Address Update Postprocessor: Allow creating Diffs for missing address

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.banking#339]
The AddressUpdate Postprocessor only creates Diffs (activities, notes, tags) when an existing address could be found, causing new addresses without an existing one not being considered a change and thus not being recorded.

There should be a new configuration attribute `create_diff_if_missing` (defaulting to `false` for backwards compatibility) which allows for a Diff to be created for new addresses.

**Comment by bjendres** [comment]
released with ``0.8.0``
