### ISSUE TITLE
Translation strings are not on Transifex

### ISSUE THREAD

**Issue by wintermoor** [Project60/org.project60.banking#350]
Some strings aren't available for translation on Transifex, although they seem to be well formatted: {ts domain='org.project60.banking'}DROP ANY CONTRIBUTION LINK IN HERE TO RECONCILE{/ts}

Example: extension/templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl 

<img width="946" alt="Fehlende Strings beim Matchen mit CiviBanking" src="https://user-images.githubusercontent.com/30273351/144274415-f0844f14-de9f-40e2-b975-45361919b5ff.png">

Does anybody know how /where to fix this?

**Comment by mlutfy** [comment]
I could not find the extension in the extension directory: https://civicrm.org/extensions

and the ext directory is what updates Transifex. I'm not sure how it ended up in Transifex in the first place.

**Comment by wintermoor** [comment]
Hej @mlutfy , it's there: https://www.transifex.com/civicrm/civicrm_extensions/civibanking/ I don't know how :)

**Comment by mlutfy** [comment]
I suspect someone added it manually, but that  bypasses the automation. Can you or the project maintainers add it to civicrm.org?

**Comment by wintermoor** [comment]
Translation strings are translated (de_DE) and packed in this extension: extension/l10n/de_DE/LC_MESSAGES/banking.po At least my missing strings are there. 

I assume that my "localization update" extension (https://github.com/cividesk/com.cividesk.l10n.autofetch) overrides the complete CiviBanking translation with the incomplete translation file from Transifex. 

Solutions: disable Localization Update OR remove CiviBanking ressource from Transifex OR add CiviBanking to https://civicrm.org/extensions

**Comment by wintermoor** [comment]
Done: disabled Localization Update, uploaded banking.po / .mo from source and cleared cache. 
Result: better translated! 

Only 3 strings are missing, I'll create a PR for this: 

#: extension/templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl
msgid "Processed manually"
msgstr "Manuell verbuchen"

#: extension/templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl
msgid "Does not belong to CiviCRM"
msgstr "Gehört nicht zu CiviCRM"

#: extension/templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl
msgid "This payment should not be reconciled with contributions in CiviCRM."
msgstr "Diese Zahlung soll nicht auf Zuwendungen in CiviCRM verbucht werden."

**Comment by wintermoor** [comment]
**Only 5 strings are not translated in CiviBanking!** They are missing in /org.project60.banking-master/extension/l10/org.project60.banking.pot and /org.project60.banking-master/extension/l10n/de_DE/LC_MESSAGES/banking.po (and .mo), too. 

Can't find them anywhere or find them well-formatted with ts+domain. Because of this I can't fix it. Maybe related: https://github.com/Project60/org.project60.banking/issues/193

Can anybody help to bring these strings in correct place?


#: extension/templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl
msgid "Processed manually"
msgstr "Manuell verbuchen"

#: extension/templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl
msgid "Does not belong to CiviCRM"
msgstr "Gehört nicht zu CiviCRM"

#: extension/templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl
msgid "This payment should not be reconciled with contributions in CiviCRM."
msgstr "Diese Zahlung soll nicht auf Zuwendungen in CiviCRM verbucht werden."

#: extension/templates/CRM/Banking/Page/Import.tpl
msgid "Upload File"
msgstr "Dateiupload"

#: extension/templates/CRM/Banking/Page/Import.tpl
msgid "Import Data File"
msgstr "Datei für den Upload"

**Comment by wintermoor** [comment]
https://lab.civicrm.org/dev/translation/-/issues/10

**Comment by wintermoor** [comment]
Related? https://github.com/Project60/org.project60.sepa/issues/519

**Comment by wintermoor** [comment]
These strings are included in plugin "Default Options", not in CiviBanking itself.
