### ISSUE TITLE
PHP 8 compatibility?

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.banking#362]
In order to avoid extensive testing on my own, I would ask if anybody else had done that before: 
Is CiviBanking already prepared for PHP 8?

**Comment by eptbertram** [comment]
Hej @Detsieber , yes, CiviBanking release 0.8.0 is ready for PHP 8! 

Testet with CiviCRM 5.53.0 WordPress Version 6.0.3 and PHP 8.0.11 and 8.1.11. Both versions are working.

**Comment by Detsieber** [comment]
Thank You @eptbertram , that's good news.

**Comment by eptbertram** [comment]
Hej @Detsieber , to be sure please check out https://github.com/Project60/org.project60.banking/issues/329
