### ISSUE TITLE
Dedupe in Civicrm not working due to error in Civibanking 0.7

### ISSUE THREAD

**Issue by DirkVran** [Project60/org.project60.banking#365]
I am using Civicrm 5.46.2 and  Civibanking 0.7. When Deduplicating a household I get the following error message :
[18-Jun-2022 21:52:30 Europe/Brussels] PHP Fatal error:  Uncaught Error: Class 'CRM_Core_EntityReference' not found in /data/sites/web/vvwzbe/www/wp-content/uploads/civicrm/ext/org.project60.banking/CRM/Banking/DAO/BankAccount.php:136
Stack trace:
#0 /data/sites/web/vvwzbe/www/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(2597): CRM_Banking_DAO_BankAccount::getReferenceColumns()
#1 /data/sites/web/vvwzbe/www/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(2625): CRM_Core_DAO::getReferencesToTable('civicrm_contact')
#2 /data/sites/web/vvwzbe/www/wp-content/plugins/civicrm/civicrm/CRM/Dedupe/Merger.php(227): CRM_Core_DAO::getReferencesToContactTable()
#3 /data/sites/web/vvwzbe/www/wp-content/plugins/civicrm/civicrm/CRM/Dedupe/Merger.php(188): CRM_Dedupe_Merger::cidRefs()
#4 /data/sites/web/vvwzbe/www/wp-content/plugins/civicrm/civicrm/CRM/Dedupe/MergeHandler.php(108): CRM_Dedupe_Merger::getActiveRelTables(3117)
#5 /data/sites/web/vvwzbe/www/wp-content/plugins/civicrm/civicrm/CRM/Dedupe/Merger.php(1582): CRM_Dedupe_MergeHandler->getTablesRelatedToTheMergePai in /data/sites/web/vvwzbe/www/wp-content/uploads/civicrm/ext/org.project60.banking/CRM/Banking/DAO/BankAccount.php on line 136

**Comment by gstester** [comment]
Same for me. We need the new version pleaaaase.

**Comment by FabianZihlmann** [comment]
Same problem for us.
Is there anybody who have any clue about how to fix it?
Thanks in advance

**Comment by bjendres** [comment]
Thanks for reporting. This is one of the items listed in #329: ``CRM_Core_EntityReference``.  

We currently don't have the funding to address this, so PR's are very welcome. If we can get some funding from our own clients, we'll be happy to let you know.

**Comment by bjendres** [comment]
Have you tried to reproduce this on the most recent version (``0.8-alpha12``), though? Just to verify this is currently still the case...

**Comment by gstester** [comment]
Seem to work


Am 20. Juli 2022 11:30:34 schrieb Björn Endres ***@***.***>:
>
> Have you tried to reproduce this on the most recent version (0.8-alpha12), 
> though? Just to verify this is currently still the case...
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: 
> ***@***.***>


Mit Aqua Mail Android
https://www.mobisystems.com/aqua-mail
