### ISSUE TITLE
CSV Importer action 'amountparse' broken

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.banking#416]
For the CSV importer to correctly import transaction amounts of 1000 or more we intruduced the ``amountparse`` CSV importer directive. This was supposed to strip any thousand separator (``.`` or ``,``) so it could be properly parsed.

However, the way the directive lookup works, the previous lookup
```
} elseif ($this->startsWith($rule->type, 'amount')) {
``` 
would always be true for ``amountparse`` as well.

As a result, the ``amountparse`` directive was *never executed*. I just wonder why this didn't come up earlier, the difference of 1000 $/£/€ would've been spottet.

I will rename the action to ``largeamount`` (because it would only affect large amounts), so existing configurations would not be affected.

**Comment by jensschuppe** [comment]
> … because it would only affect large amounts …

Pre-2002 Italian lira would disagree :wink: :it:

**Comment by bjendres** [comment]
> > … because it would only affect large amounts …
> 
> Pre-2002 Italian lira would disagree 😉 🇮🇹

It would still be large amounts....of low value lira :) I does feel good to to large amounts, though :) 

*fondly remembers visiting 🇨🇱*

**Comment by bjendres** [comment]
Released with CiviBanking-0.8.4
