### ISSUE TITLE
Translation not working: missing 'domain' argument for ts()

### ISSUE THREAD

**Issue by Awem** [Project60/org.project60.banking#81]
My CiviCRM 4.5.5 (Drupal 7.34) installation is set to german and was installed with l10n files in place. The majority of the user interface is correctly translated. However, some extensions not. This extension comes with german l10n files, but it is not translated. Under "Banking" in the menu, only two items are listed under a german title "Übersichtseite" and "Konfiguation" (no typo). Why are the l10n files not used? Maybe it uses incomplete transifex ressources instead?
I'm using native gettext support via `define('CIVICRM_GETTEXT_NATIVE', 1);` in _civicrm.settings.php_. I also installed the german locale on the server. This works well for the main application, but whether I use this or remove that line not does not make a difference for e.g. CiviBanking.
The main CiviCRM-l10n-files show a folder structure with _LC_MESSAGES_-folder (also see https://issues.civicrm.org/jira/browse/CRM-13068 and the note here: http://wiki.civicrm.org/confluence/display/CRMDOC41/CiviCRM+Localisation#CiviCRMLocalisation-Usingnativegettextsupport). Maybe this extension has to use that structure? If I use the com.cividesk.l10n.update extension (https://github.com/cividesk/com.cividesk.l10n.update), it puts an empty _banking.mo_ in _/sites/default/files/civicrm/extensions/org.project60.banking/l10n/de_DE/LC_MESSAGES_.
So that extension suggests that structure, albeit there is no proper trasnslation hosted at https://github.com/civicrm/civicrm-l10n-extensions. However, replacing that _banking.mo_ with the downloaded _org.project60.banking/master/l10n/CiviBanking_de_DE.mo_ does not help. So there must be some other problem.
Do I have to reconfigure anything or does this extension need to be refactored to use _civicrm-l10n-extensions_?

**Comment by AW-UC** [comment]
Ok, the issue is cause by a missing 'domain' argument for ts(). Maybe there also some linebreaks in connection with ts() - haven't checke though. See this pull request for an overview of the needed changes: https://github.com/progressivetech/net.ourpowerbase.sumfields/pull/2
That extensions had the same issue. Also see this post for additional clarification: http://forum.civicrm.org/index.php/topic,35629.msg151462.html#msg151462

**Comment by systopia** [comment]
(finally) picked up by #125, and hopefully happening in 0.5.4
