### ISSUE TITLE
Access permission Civibanking menu

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.banking#88]
It seems the banking menu item added by civibanking has no access control limitation.
Even if it would be hardcoded it would seem reasonable that 'access CiviContribute' permission would be set.
Right now, all people with 'access civicrm' see the menu item which for them is confusing.

**Comment by systopia** [comment]
Maybe I'll set this to edit contributions for the time being. 

In the long run we will -of course- have a permission model, see https://github.com/Project60/org.project60.banking/issues/95

**Comment by dragonjon** [comment]
Hello @magnolia61 and @systopia 
I modify the file hooks.php in the line 67 'permission' => null, to 'permission' => 'access CiviContribute',

I need to do the same only access from users with access CiviContribute in the tab of Banking Accounts in contacts but I can not do it. One help please
